### ISSUE TITLE
Auditor crashes when Display Size set to Largest

### ISSUE THREAD

**Issue by TheEarlOfEmsworth** [GrapheneOS/Auditor#120]
When screen size is set to largest, auditor crashes when the camera is opened for auditoring or auditeeing.

RQ3A.20210905.001
Pixel 3XL

**Comment by thestinger** [comment]
@TheEarlOfEmsworth 

Please test with this v32-alpha release.

[Auditor-32-alpha.apk.zip](https://github.com/GrapheneOS/Auditor/files/7191135/Auditor-32-alpha.apk.zip)

**Comment by thestinger** [comment]
I had to put it in a zip file to upload it to GitHub so you'll need to extract it from there.

**Comment by thestinger** [comment]
This will be resolved in v32 coming soon.

**Comment by TheEarlOfEmsworth** [comment]
Thanks to you both!

Really appreciate you fixing this, and all that you do generally.

Unfortunately though Auditor is still crashing for me. I've captured a bug report (bear with me, I'm not a developer) but is there somewhere I can send it to that isn't so public?

**Comment by thestinger** [comment]
You can send it to @strcat:grapheneos.org on Matrix.

**Comment by thestinger** [comment]
Have you tried v32 already? You'll need to manually install the update since it's not released for the OS yet.
