### ISSUE TITLE
pwned ?

### ISSUE THREAD

**Issue by Jabol07** [GrapheneOS/Auditor#137]
hi, how can i know im pwned ? coz i lost vonnevtion with second phone and i getting emails that someone trying to login to my account...
![18c09a284cca3247d62e28b3d57cfeee8f879e54_2_460x1000.png](https://user-images.githubusercontent.com/93392418/140661237-c7091e67-f5b4-4721-acb6-9d8a745e1ea9.png)
ive got adwert like this in ranfom time mostly with google.com site but that one was blind...

**Comment by thestinger** [comment]
Can't help you with this, sorry. Not a good fit for the Auditor issue tracker. If it's about GrapheneOS ask for help from the chat rooms. If it's about something else, we can't help.
