### ISSUE TITLE
Crashes when no rear-camera available

### ISSUE THREAD

**Issue by astonishingriverboat** [GrapheneOS/Auditor#176]
### Auditor release
44

### Brief summary
My Pixel 3a currently has no rear-camera.
And when trying to verify my device (scanning a QR Code), the app crashes and reopens with a blank layout (meaning without the buttons).

### Steps to reproduce
- Uninstall rear-camera
- Open Auditor
- Select "Auditee (device being verified)"

### Expected behaviour
Automatically use existing front-camera.
And if no camera available, display something along the lines of "No Camera Found".

### Actual behaviour
QR scanner is open for about 4 seconds, then the app crashes and reopens with a blank layout (meaning without the buttons).

**Comment by thestinger** [comment]
It should now show an error message instead of crashing but we haven't implemented a fallback feature yet.

**Comment by thestinger** [comment]
This will be fixed in the next release.

**Comment by thestinger** [comment]
Please try version 50:

https://github.com/GrapheneOS/Auditor/releases/tag/50

**Comment by astonishingriverboat** [comment]
It works, thank you very much.
