### ISSUE TITLE
Verification failure

### ISSUE THREAD

**Issue by Umlaut512** [GrapheneOS/Auditor#210]
I have seen 2 remote verification failures in the last week and i am wondering if it is a bug.
![Screenshot_20220928-073731](https://user-images.githubusercontent.com/112734831/193276780-6d08905b-0fab-4d80-bc0b-44d53482ef59.png)
![Screenshot_20220930-150656](https://user-images.githubusercontent.com/112734831/193276786-9a054f64-5b7b-4fd3-b7ba-acd4d457a14b.png)

**Comment by thestinger** [comment]
It's not a bug. This is a network issue on your end.
