### ISSUE TITLE
Pixel 7 failed to submit remote attestation

### ISSUE THREAD

**Issue by DOFfactory** [GrapheneOS/Auditor#213]
Hello, new user of GrapheneOS. Installed yesterday and also added most of the apps I needed and created 2 users. 

This morning I was welcomed by 2 messages: 

1. Device is fully up-to-date
2. Remote verification failure - Failed to submit remote attestation

The details of the 2nd say: `java.security.GeneralSecurityException: wrong attestation app package name: UnknownPackage`

Can you please tell me what it wrong and help me to troubleshoot?

**Comment by thestinger** [comment]
Try fully powering it off and then turning it back on. We've seen this issue on past generation devices as a known bug in the Titan M(2) firmware.

**Comment by DOFfactory** [comment]
Thanks, just did so, hopefully it will fix it.

**Comment by DOFfactory** [comment]
Can I have a follow-up question please? So I restarted the device, and the attestation app was reporting that all is fine. However, I have 2 accounts on the device (personal and work). The auditor reported that all is fine on the personal account, and in the work account it was showing an error, which I dismissed, and now I received an email stating: `Devices failed to provide valid attestations within 48 hours`

I restarted the device and logged in again to both of the accounts, but I wonder whether I am doing something wrong, or will this be fixed in the near future? Thanks for your comments in advance!
