### ISSUE TITLE
Remote attestation failure due to invalid number of Auditor app signatures

### ISSUE THREAD

**Issue by fourpartswater** [GrapheneOS/Auditor#237]
I have a new Pixel 6a with GrapheneOS installed yesterday.

I set up remote attestation and it was successful for the first few attestations. It has now stopped functioning with the following error from the Auditor app;

Remote verification failure 
Failed to submit remote attestation.
java.security.GeneralSecurityException: Invalid number of Auditor app signatures.

**Comment by thestinger** [comment]
This is a known firmware bug. You need to reboot the device.
