### ISSUE TITLE
P8 running GrapheneOS reporting Remote Verification Failure

### ISSUE THREAD

**Issue by snrkl** [GrapheneOS/Auditor#247]
Unsure if this should be in the OS tracker or the auditor. If this is the wrong place let me know and I will re-open in the correct issue stack.

GrapheneOS on P8 Build UQ1A.231205.015.2023120800
app.attestation.auditor Version 77

Notification received:

> **Remote Verification Failed**
> Failed to submit remote attestation
> java.security.GeneralSecurityException: invalid number of Auditor app signatures

Error also occurs when I try to audit locally with a previously paired device.

![Screenshot_20231213-080647~2](https://github.com/GrapheneOS/Auditor/assets/2288035/6aefcd3b-d515-492e-a39b-7889277d8ae8)

**Comment by thestinger** [comment]
It's a known Android / firmware bug, you just need to reboot.

**Comment by thestinger** [comment]
Auditor is correct that it's wrong.

**Comment by snrkl** [comment]
Thanks @thestinger - can confirm this worked..
