### ISSUE TITLE
Pixel Tablet (`tangorpro`) can't scan QR code as auditor device on Pixel phone auditees

### ISSUE THREAD

**Issue by taivlam** [GrapheneOS/Auditor#248]
I'm experiencing a UX issue when attempting a manual check when the Pixel Tablet (`tangorpro`) is the auditor and any of the smaller Pixel phone devices are the auditees: Pixel Tablet can't scan the more dense second QR code on the Pixel phone.  Also, the Pixel Tablet's rear camera only has an 8MP sensor, while the Pixel 4a and Pixel 5a's main rear cameras have 12.2MP sensors.

As the camera focus is fixed while scanning QR codes, the Pixel Tablet can never scan the second QR code on the Pixel phone.  There are only 2 outcomes I can try, neither which work:
* either I hold the Pixel Tablet as close to the Pixel phone as close as possible to fill up the indicated square in the Auditor app's viewfinder for the second QR code, only for the dense QR code to be blurry and thus unreadable to the Pixel Tablet; or
* I hold the Pixel Tablet far enough away that the second QR code is in focus, but this comes at the cost of the QR code being too small in the viewfinder's square (taking up 25% of the scannable square area).

The above was experienced when using Auditor between Pixel Tablet and Pixel 5a.

I don't know if I'm doing something wrong, but I've been able to set up manual checking and remote attestation between these devices: Pixel 4a (`sunfish`), Pixel 5a (`barbet`), and Pixel 6a (`bluejay`).

I've scanned plenty of QR codes before and also have done a few QR code scans in Auditor, so I'm fairly confident that I didn't break the Pixel Tablet's camera or I am using the QR scanning wrong.  I was able to scan the second QR code in the native GrapheneOS Camera app by being able to manipulate the camera zoom (so the second QR code is functioning properly), but this is not possible in Auditor.  I've tried everything from adjusting the angle/position I held the Pixel Tablet to adjusting the screen brightness, but it didn't change anything for me.

(However, the reverse situation UX works fine: a smaller Pixel phone being the auditor and the Pixel Tablet being the auditee.)

(I also am guessing that if I did a manual pairing between two Pixel Tablets in Auditor, then both would be able to work and this UX issue would not happen - but I don't have a second Pixel Tablet and/or another Android tablet that works with Auditor to test this hypothesis out.)

I can make a short video of this, if I need to clarify what I mean from above.

**Comment by thestinger** [comment]
Pixel Tablet camera is quite bad and the QR code from the Auditee is very dense. We can probably improve this but it's hard to make it scan well.

**Comment by taivlam** [comment]
It's been about 1 month, though I wanted to say that there has been (at least) 1 update to Auditor since my previous post.  I'm glad to say that I'm able to successfully perform a manual verification between the Pixel 5a and Pixel Tablet in both directions now.  A little finessing while positioning the Pixel Tablet to scan the second QR code on the Pixel 5a, but ultimately it can be done.

However, I haven't been able to conduct a manual verification when Pixel Tablet is the auditor and the Pixel 4a is the auditee for the same reason (the second QR code is too dense on the Pixel 4a for the Pixel Tablet).

I'm only bringing up the Pixel 4a, since there could be similarly sized devices that are currently on (or will be added in the future) to the [list](https://attestation.app/about#device-support) of supported devices for the Auditor app; and this UX issue could crop up for anyone who tries to use a Pixel Tablet sized device as the auditor and a Pixel 4a-sized device as the auditee.

(Though this is sort of a "nitpick" as an edge case with the UX, as for all practical intents and purposes I've stopped using the Pixel 4a, since it's on extended legacy support for GrapheneOS; a manual verification in both directions between the Pixel 5a and Pixel Tablet was all I needed for confidence before adding remote attestation to the Pixel Tablet.)

**Comment by thestinger** [comment]
There's not much we can do about the low quality camera on the Pixel Tablet. We don't plan to make the system for relaying the attestation more complex than a QR code. Unless there's a proposal about what we could do to make it easier to scan, we'll have to close this as non-actionable. Improvements can be made to QR scanning but issues need to be actionable and about something concrete. Given enough effort, you can scan the QR code with the Pixel Tablet, but it may require particularly good lighting, holding it at a good distance, etc.
