### ISSUE TITLE
Verification of GrapheneOS on blueline gives an error

### ISSUE THREAD

**Issue by nutts0** [GrapheneOS/Auditor#52]
I tried to verify the pixel 3 (GrapheneOS) with a pixel 3 stock.

![](https://i.imgur.com/P8YLlWF.png)
![](https://i.imgur.com/0GnINgy.png)

The GrapheneOS phone successfully verified the stock

![](https://i.imgur.com/OovZxjt.png)

**Comment by thestinger** [comment]
Is it possible your time is out of sync on one of the devices?

**Comment by nutts0** [comment]
Will check it

**Comment by nutts0** [comment]
Yes indeed the time was wrong on the grapheneos device

**Comment by thestinger** [comment]
I could probably provide a better error in this case.

**Comment by thestinger** [comment]
Related:

https://github.com/GrapheneOS/Auditor/issues/37
https://github.com/GrapheneOS/Auditor/issues/38
