### ISSUE TITLE
Spam (phishing?) mail to a web attestaion assigned email alias

### ISSUE THREAD

**Issue by bungabunga** [GrapheneOS/Auditor#63]
hi!

i don't know if this is the proper place to post this, spare me criticism if it is not so, for i am doing it with good intentions.

recently i received an email that rightfully ended in my spam folder and it could also be a phishing attempt. the problem is that i received it to an email alias that was made and is used only to connect to attestation web page and nothing else. my email web login is also protecte by 2FA with a yubikey and no phone number. so my guess is the email adress probably leaked to the spammers from your side. what do you think?

thanks!
![spammaybephishing](https://user-images.githubusercontent.com/2994878/71748238-321afb80-2e72-11ea-99ef-7e88d4b7819c.jpg)

**Comment by thestinger** [comment]
Nothing is leaked, you're wrong.

**Comment by beerisgood** [comment]
@bungabunga 
Email adresses can easy tested by bots and other methods
