### ISSUE TITLE
Auditor app crashes on initial device pairing

### ISSUE THREAD

**Issue by Jawshy** [GrapheneOS/Auditor#64]
The Auditor app keeps stopping when attempting to perform the initial pairing between a phone and tablet. 

Auditor: Google Pixel 3a XL [Model: G020B]
Auditee: Galaxy Tab A 10.1 2019 (Wi-Fi) [Model: SM-T510]

Both devices are running Auditor version 17. 

Steps to reproduce issue: 
1. Launch Auditor on both devices.
2. Tap 'auditor (device performing verification)' on the Pixel.
3. Tap 'auditee (device being verified)' on the Tab A.
4. Scan QR code shown on the other device.
5. The app crashes. 

No issues when auditor and auditee are switched; pairing and verification are successful. 

Please let me know if additional information is needed.

**Comment by thestinger** [comment]
Can you trigger the crash and then go into developer options and use the take bug report feature to send a bug report to contact@attestation.app? Note that the bug report zips may contain some sensitive data if crash dumps or logs contain it.

Alternatively, you could use ADB to run `adb logcat` on an attached + whitelisted host computer and then trigger the crash.

It's likely that a minor mistake was made in the metadata added to support this tablet which will need to be corrected.

**Comment by Jawshy** [comment]
Sent 📬

**Comment by thestinger** [comment]
@Jawshy Can you check if this is still a problem and send another bug report?

**Comment by Jawshy** [comment]
The app still crashes on the tablet. I've sent a bug report to contact@attestation.app

**Comment by thestinger** [comment]
@Jawshy I think https://github.com/GrapheneOS/Auditor/commit/ce8c0f464ec25daa7c690a2030620c34b84f300c will fix the issue. I can make a test release for you to try on the Auditee.

**Comment by thestinger** [comment]
It might be better to just make a normal release due to how Auditor releases impact attestation.

**Comment by thestinger** [comment]
Adjusted this to https://github.com/GrapheneOS/Auditor/commit/a0cc37c35dbcad8463886bff3d44666a2cd9467a to avoid weakening the check on other devices.

**Comment by thestinger** [comment]
This will be fixed by the next release when I finally find the time to put that together...

**Comment by thestinger** [comment]
@Jawshy This is FINALLY released in version 18. Sorry it took so long.

**Comment by Jawshy** [comment]
I updated Auditor to version 18 on both devices and tried verifying the tablet again. The app didn't crash, but the verification failed on the first attempt. Upon clearing the auditee parings, the initial pairing was successful on the second attempt. Cheers.

**Comment by thestinger** [comment]
It probably failed due to the previous failed pairing. If the pairing is incomplete, the device being audited doesn't actually know that.
