### ISSUE TITLE
Cannot verify my Huawei Mate 20 lite

### ISSUE THREAD

**Issue by mads256h** [GrapheneOS/Auditor#66]
When i scan the QR code from the Auditor i get the following error:
```
Error encountered generating attestation:
Key not yet valid
```

**Comment by thestinger** [comment]
It sounds like your clock is set incorrectly on one of the devices.

**Comment by mads256h** [comment]
I have checked both and they are set right

**Comment by mads256h** [comment]
Rebooted both devices again and it now works! 🤷
