### ISSUE TITLE
Samsung device that is listed as "supported" cannot be audited 

### ISSUE THREAD

**Issue by solarelf** [GrapheneOS/Auditor#70]
Hi,

according the table,Samsung Galaxy Tab S4 (T835) is a supported one. However it seem that my device, which is T835N (LTE model) is not on the list. I get  the message "device is not on list when I press "this device is auditee".

I have submitted sample data and I hope you will add support for my device as well, but I wonder why so?

The OS is Android 10 

![Screenshot_20200901-183344_Auditor](https://user-images.githubusercontent.com/42090132/91874229-a23c8400-ec82-11ea-81d4-05c9a067c33c.jpg)

**Comment by thestinger** [comment]
T835N is a different model. This will have to be handled with adding support for other devices. We're not currently actively doing that due to lack of available resources.
