### ISSUE TITLE
Auditor 19 not working on Pixel 3a (RP1A.200720.009.2020.09.18.13)

### ISSUE THREAD

**Issue by n1m1** [GrapheneOS/Auditor#71]
I have recently upgraded my Pixel 3a from Android 10 (QQ3A.200805.001.2020.09.10.05) to Android 11 (RP1A.200720.009.2020.09.18.13). Everything works just fine but Auditor. 

* Local verification does not work: after scanning the QR code which appears on the device performing verification, the following error message appears on my phone

`android.content.pm.PackageManager$NameNotFoundException:net.typeblog.shelter`

* Scheduled verification does not work neither. When I scan the QR code on attestation.app my phone says:

`Failed to submit remote attestation`

Never had a problem earlier. Both local and remote verification have always worked perfectly.

Thanks

P.s: I have also tried to reboot my phone (as it seems this helped some users to the issues they have experienced after the upgrade to Android 11) but it did not work.

**Comment by thestinger** [comment]
The issue seems to be that API 30+ forbids querying information about other packages by default.

https://github.com/GrapheneOS/Auditor/commit/32353d3a68b622cc44a7bdd0e23a3e6334cb7302 should address this problem. Hopefully this doesn't become a problem for this app on the Play Store in the future.

**Comment by thestinger** [comment]
Try version 20:

https://github.com/GrapheneOS/Auditor/releases/tag/20

**Comment by n1m1** [comment]
Hi and thanks for this.
I've just tested Auditor 20 with the new GrapheneOS beta release (RP1A.200720.009.2020.09.29.20). Unfortunately it does not seem to work.

* Scheduled remote verification does not work. When I scan the QR code on attestation.app my phone says:

`Failed to submit remote attestation`

* Local verification does not work. My phone says:

`Error encountered generating attestation: 
Failed to verify certificate`

I am using Auditor 20 either on Pixel 3a and on the device performing verification. Before testing the new Auditor version I have 

- Cleared Auditor pairings
- Cleared Auditee pairings
- Disabled remote verification
- Clear Auditor's cache and data on both pones.

Cheers

**Comment by iNorman77** [comment]
Hi! I done all of these clean clear disable still the same. Unfortunately headache tbh. Norma-01.10.2020, 12:15 pm, "n1m1" <notifications@github.com>:
Hi and thanks for this.
I've just tested Auditor 20 with the new GrapheneOS beta release (RP1A.200720.009.2020.09.29.20). Unfortunately it does not seem to work.

Scheduled remote verification does not work. When I scan the QR code on attestation.app my phone says:

Failed to submit remote attestation

Local verification does not work. My phone says:

Error encountered generating attestation:  Failed to verify certificate
I am using Auditor 20 either on Pixel 3a and on the device performing verification. Before testing the new Auditor version I have

Cleared Auditor pairings
Cleared Auditee pairings
Disabled remote verification
Clear Auditor's cache and data on both pones.

Cheers

**Comment by thestinger** [comment]
You should file separate issues for different issues. The issue this thread was created about is definitely fixed.
