### ISSUE TITLE
Pixel 4 XL cannot be verified after change of rom from GrapheneOS

### ISSUE THREAD

**Issue by githupper** [GrapheneOS/Auditor#73]
Error encountered generating attestation. 
Failed to verify certificate Certificate.

fastboot erase avb_custom_key was ran during the change to stock rom before locking bootloader.

**Comment by thestinger** [comment]
It sounds like there's genuinely an error verifying the certificate chain. You aren't posting the full error message so there's not much more that can be said about it. Perhaps you have the clock set wrong on one of the devices.

**Comment by githupper** [comment]
Just so you know, your latest version fixes the issue.

**Comment by thestinger** [comment]
Well, it doesn't fix the issue, but it works around it.

**Comment by githupper** [comment]
Saw #74 

My log from his/her are totally different , saved for the first few lines. Mine is all gibberish without readable text like the  java messages hence did not paste the full log.

Anyway, thanks for the quick workaround
