### ISSUE TITLE
replace JCenter with Maven Central or other repo

### ISSUE THREAD

**Issue by inthewaves** [GrapheneOS/Auditor#86]
We're using JCenter for some dependencies: https://github.com/GrapheneOS/Auditor/blob/master/build.gradle#L6

But https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ says,

> To streamline the productivity of the JFrog Platform we will be sunsetting Bintray (including JCenter), GoCenter, and ChartCenter services on May 1st, 2021. Users of these services will need to migrate to the respective canonical repository, and we will continue to offer both free and paid JFrog Platform cloud subscriptions that can serve other binary distribution needs. Additionally, JFrog is partnering with hubs like Docker to help ensure that infrastructure our customers and community depend upon is well maintained.

Trying to replace JCenter with Maven Central results in the following sync error:

```plain
A problem occurred configuring root project 'Auditor'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.jetbrains.trove4j:trove4j:20160824.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
     Required by:
         project : > com.android.tools.build:gradle:4.1.2 > com.android.tools.build:builder:4.1.2 > com.android.tools:sdk-common:27.1.2

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Same issue described in https://github.com/signalapp/Signal-Android/issues/10906#issuecomment-774770426, so I guess we'd have to wait for now

**Comment by inthewaves** [comment]
trouve4j-20160824 on Maven Central is tracked at https://youtrack.jetbrains.com/issue/IDEA-261387#focus=Comments-27-4675742.0-0

**Comment by inthewaves** [comment]
Blog post has been updated: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

> UPDATE: To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st 2021.
>
> To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021.

**Comment by inthewaves** [comment]
Another issue: We are using `me.dm7.barcodescanner:zxing:1.9.13`, but 1.9.13 is only available on JCenter: https://mvnrepository.com/artifact/me.dm7.barcodescanner/zxing?repo=jcenter

**Comment by thestinger** [comment]
We could see if we could copy the QR scanning code in the Settings app for Wi-Fi network sharing.

**Comment by thestinger** [comment]
This is done.
